settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: compare-dev-uks
    name: compare-dev-uks
    url: 'https://compare-dev-uks.sb2.dev/api/string?code=KoHwuxanRLNM3NiKUpsuVgRCpt7kOGKTGCskNnbS5GrWT9XoyseNmA==&text1=simila&text2=similar'
    method: GET
    expectStatus: 200
    
  - id: sanitise-dev-uks
    name: sanitise-dev-uks
    url: 'https://sanitise-dev-uks.sb2.dev/api/emojis?code=IvAK8XT72Hmi6KBb9ni0/fv/fHUB6XbibaEXyWGy/JsplstEkMdzVA==&data=you-%F0%9F%91%8F-can-%F0%9F%91%8F-put-%F0%9F%91%8F-emjois-%F0%9F%91%8F-in-%F0%9F%91%8F-urls-%F0%9F%91%8F/'
    method: GET
    expectStatus: 200

  - id: spelling-dev-uks
    name: spelling-dev-uks
    url: 'https://spelling-dev-uks.sb2.dev/api/correct?code=qKXeDWrtOaa7ataMfObbt6nsOmF8MbZOAgsq1SaRmauFAhaKScevbw==&word=incorect'
    method: GET
    expectStatus: 200
