settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: compare-afd
    name: compare-afd
    url: 'https://toastly.sb2.dev/api/string?&text1=simila&text2=similar'
    method: GET
    expectStatus: 200
    
  - id: sanitise-afd
    name: sanitise-afd
    url: 'https://toastly.sb2.dev/api/emojis?&data=you-%F0%9F%91%8F-can-%F0%9F%91%8F-put-%F0%9F%91%8F-emjois-%F0%9F%91%8F-in-%F0%9F%91%8F-urls-%F0%9F%91%8F/'
    method: GET
    expectStatus: 200

  - id: spelling-afd
    name: spelling-afd
    url: 'https://toastly.sb2.dev/api/correct?&word=incorect'
    method: GET
    expectStatus: 200

  - id: compare-dev-uks
    name: compare-dev-uks
    url: 'https://toastly-func-d-uks-compare.azurewebsites.net/api/string?&text1=simila&text2=similar'
    method: GET
    expectStatus: 200
    
  - id: sanitise-dev-uks
    name: sanitise-dev-uks
    url: 'https://toastly-func-d-uks-sanitise.azurewebsites.net/api/emojis?&data=you-%F0%9F%91%8F-can-%F0%9F%91%8F-put-%F0%9F%91%8F-emjois-%F0%9F%91%8F-in-%F0%9F%91%8F-urls-%F0%9F%91%8F/'
    method: GET
    expectStatus: 200

  - id: spelling-dev-uks
    name: spelling-dev-uks
    url: 'https://toastly-func-d-uks-spelling.azurewebsites.net/api/correct?&word=incorect'
    method: GET
    expectStatus: 200
    
  - id: compare-dev-ukw
    name: compare-dev-ukw
    url: 'https://toastly-func-d-ukw-compare.azurewebsites.net//api/string?&text1=simila&text2=similar'
    method: GET
    expectStatus: 200
    
  - id: sanitise-dev-ukw
    name: sanitise-dev-ukw
    url: 'https://toastly-func-d-ukw-sanitise.azurewebsites.net/api/emojis?&data=you-%F0%9F%91%8F-can-%F0%9F%91%8F-put-%F0%9F%91%8F-emjois-%F0%9F%91%8F-in-%F0%9F%91%8F-urls-%F0%9F%91%8F/'
    method: GET
    expectStatus: 200

  - id: spelling-dev-ukw
    name: spelling-dev-ukw
    url: 'https://toastly-func-d-ukw-spelling.azurewebsites.net/api/correct?&word=incorect'
    method: GET
    expectStatus: 200
